### ISSUE TITLE
request with no body can not apply gzip middleware

### ISSUE THREAD

**Issue by beihaifeiwu** [hertz-contrib/gzip#6]
**Describe the bug**

request with no body can not apply gzip middleware

**To Reproduce**
both client and server middleware has the same problem, eg: get request with no body

**Expected behavior**

request with no body work as expected

**Comment by li-jin-gou** [comment]
refer to https://github.com/hertz-contrib/gzip/blob/main/srv_middleware.go#L80 and most scenarios where gzip is used are for compressing the body, but here it is possible to allow the user to customize the logic to continue. 
I added it to the todo and welcome to make a pull request.

**Comment by beihaifeiwu** [comment]
also this one [https://github.com/hertz-contrib/gzip/blob/faffd46f03ffb638e5886ebd8798c49ce8f0e74c/client_middleware.go#L79](https://github.com/hertz-contrib/gzip/blob/faffd46f03ffb638e5886ebd8798c49ce8f0e74c/client_middleware.go#L79)

**Comment by beihaifeiwu** [comment]
```go
func TestGzipForClient(t *testing.T) {
	h := server.Default(server.WithHostPorts("127.0.0.1:2333"))

	h.GET("/ping", func(ctx context.Context, c *app.RequestContext) {
		c.Header("Content-Length", strconv.Itoa(len("Gzip Test Response")))
		c.String(200, "Gzip Test Response")
	})
	go h.Spin()
	time.Sleep(time.Second)

	cli, err := client.NewClient()
	if err != nil {
		panic(err)
	}
	cli.Use(gzip.GzipForClient(gzip.DefaultCompression))

	req := protocol.AcquireRequest()
	res := protocol.AcquireResponse()

	// req.SetBodyString("bar")
	req.SetRequestURI("http://127.0.0.1:2333/ping")

	cli.Do(context.Background(), req, res)
	if err != nil {
		t.Fatalf("Get: %v", err)
	}

	assert.Equal(t, res.StatusCode(), 200)
	assert.Equal(t, string(res.Body()), "Gzip Test Response")
	// assert.Equal(t, req.Header.Get("Vary"), "Accept-Encoding")
	// assert.Equal(t, req.Header.Get("Content-Encoding"), "gzip")
	// assert.NotEqual(t, req.Header.Get("Content-Length"), "0")
	// assert.NotEqual(t, fmt.Sprint(len(req.Body())), req.Header.Get("Content-Length"))
}
```
this test will fail, but it shouldn't

**Comment by welkeyever** [comment]
Thanks for your report! I will take a look at it soon 🙏
